spring.application.name=hackhub

# console H2 abilitation
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
logging.level.org.springframework.boot.autoconfigure.h2=DEBUG



#  datasource configuration
spring.datasource.url=jdbc:h2:file:./database/hackhub
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


jwt.secret=K7gNU3sdo+OL0wNhqoVWhr3g6s1xYv72ol/pe/Unols=
jwt.expiration=86400000